name: Deploy Javadoc

on: [push, pull_request]

jobs:
  publish:
    strategy:
      fail-fast: false
      matrix:
        os: [windows-latest, windows-2019, windows-2016]
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v2
      - name: Generate Javadoc
        run: .\gradlew.bat aggregateJavadoc
      - name: Deploy Javadoc
        uses: JamesIves/github-pages-deploy-action@3.5.9
        with:
          branch: javadoc
          folder: build/docs/aggregateJavadoc
          target_folder: javadoc
